### PR TITLE
Statfactor output

### PR DESCRIPTION
**Pull request by johnsekar**
Outputs automorphism calculations for each rule. If generate_network() is called in the model, outputs lumping factors for each reaction generated from each rule.

USAGE:
perl BNG2.pl model.bngl --write_autos
(or)
perl BNG2.pl model.bngl --autos

### CODE REVIEW

**Comment by johnsekar** [comment]
The fail is associated with assuming $rxn->RxnRule->Name exists when building a reaction, but that does not have to be the case if the user did not specify a name for the rule.

**Comment by jjtapia** [comment]
Other validation files where the user doesn't define a rule name seem to pass the validation test like blbr.bngl. The problem seem to be associated instead when reactions are loaded from a .net file, reaction names are not populated.

**Comment by johnsekar** [comment]
RxnList->readString() (which is used in readFile() for reading a reaction list), also calls RxnList->add(), which then tries to query the name of the rule because of my edit.  I think it can be solved by hiding the call to RxnRule->Name within an 'if' block.

**Comment by jjtapia** [comment]
That sounds like it could work as long as it's properly commented. The only issue is that the logic of the function becomes a little unintuitive and dependent on who calls the function, which is typically not recommended. The main issue becomes then if you think those write_output preprocessing lines belong in the RxnList:add function or if they could be moved elsewhere.

**Comment by johnsekar** [comment]
Unfortunately it has to be in the add() function. As and when a new reaction is added that matches an old reaction, add() lumps them in place, so that's where you can detect and calculate the lumping factor.

**Comment by jjtapia** [comment]
In that case let's go with the check for whether the RxnRule->name exists. Just add those comments and we should be good.

**Comment by johnsekar** [comment]
What's the advantage between checking for RxnRule->Name vs just checking for $BNGModel::GLOBAL_MODEL->Params->{'write_autos'} ?

**Comment by jjtapia** [comment]
ah, that's right, you have your own flag. In that case go for that one. It  helps making the code a little more self explanatory.

**Pull request closed without merging**
