### PR TITLE
Implementation of the heterogeneous adaptive scaling method

### PR DESCRIPTION
**Pull request by LifeWorks**
This heterogeneous adaptive scaling method (HAS) is developed by Song Feng (@LifeWorks) in Hlavacek group in Los Alamos National Laboratory.

The basic idea is using heterogeneous scaling factor for each reaction combined with an adaptive update scheme for these scaling factors to speed up the simulation while maintaining the first moment accuracy. 

With implementation of HAS method, new simulation method is added "has", as well as  options such as "scalelevel" and "check_product_scale" in the simulation method "has" and "ssa".

The detail of the implementation and benchmarks will be available in the research paper that is currently in preparation.

### CODE REVIEW

**Comment by jrfaeder** [comment]
Hi Song, 

Thanks very much for your contribution. It sounds exciting and I'm looking forward to trying it out. We are currently in the process of working out some glitches in our build process (and preparing for a workshop the week of 3/5), but we will check the code and get it integrated or get back to you in the near future if there are any problems.

Best regards,

Jim

**Comment by jrfaeder** [comment]
Hi Song,

I just had a quick look and the code looks great and well-integrated into the existing framework. It looks like it should be very easy for a BNG user to use with an existing. I would like to make two requests:
1. Can you provide a **simple example model** that illustrates use of the method. It could be added to the Models2 directory. 
1. Can you provide at least **one test** (possibly using the same model) that would go in the Validate directory? This will help to ensure that future changes to the code don't interfere with the HAS functionality.

If you have concerns about providing more code or details before submitting the paper, I understand. These items could be added later.

Thanks,

Jim

**Comment by LifeWorks** [comment]
Hi Jim,

I am currently preparing the example model and test files. Bill also suggested so.

When I have them ready, I will create a new pull request.

Best!

Song

**Comment by jrfaeder** [comment]
That's fantastic, thanks!

**Comment by LifeWorks** [comment]
Hi Jim,

I added one example file and its test files for the HAS method. I tested and validated on my own workstation (linux). The validation passed.

Best!

Song

**Comment by LifeWorks** [comment]
Hi Jim,

It seems the test on windows has failed, I set seed for stochastic simulation. And it is the species trajectories are different. Does the random number generator used in BNG behaves the same in linux and windows?

Thanks

Song

**Comment by LifeWorks** [comment]
Hi Jim,

Please let me know if there are more things need to be done. Meanwhile, I am working on implementing the same idea in NFsim.

Best!

Song

**Pull request merged**
